### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by polRk** [ydb-platform/ydb-slo-action#4]
## Integrations
- [ ] Go SDK [ydb-go-sdk](https://github.com/ydb-platform/ydb-go-sdk)
- [ ] Java SDK
- [ ] Python SDK
- [ ] Nodejs SDK

## Functionality
- [ ] Supports user defined custom metrics
- [ ] Supports user defined report template
- [ ] Chaos testing tool
